routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
  Route::get('/home', 'HomeController@index')->name('home');

  Route::resource('items', 'ItemController');
  Route::resource('pos', 'PosController');
  Route::resource('sales', 'SaleController');
  Route::resource('customers', 'CustomerController');
  Route::resource('suppliers', 'SupplierController');
  Route::resource('receivings', 'ReceivingController');
  Route::resource('por', 'PorController');
  Route::get('items/{id}/copy','ItemController@copy');
  Route::resource('stocks', 'StockController');
  Route::resource('prices', 'PriceController');
  Route::resource('checkprice', 'CheckPriceController');
  Route::resource('invoices', 'InvoiceController');
  Route::get('sales/{order_id}/makeinvoice','SaleController@makeInvoice');
  Route::get('receivings/{order_id}/makeinvoice','ReceivingController@makeInvoice'); // TODO: cambiar a ORDER
  //Route::resource('users', '\Cobierto\Acl\Controllers\UserController');
  //Route::resource('roles', '\Cobierto\Acl\Controllers\RoleController');

});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Item extends Model
{

  public $visible = [
          'id',
          'upc_ean_isbn',
          'name',
          'description',
          'avatar',
          'cost_price',
          'selling_price',
          'quantity',
          'is_item_kit',
          'is_stockeable',
          'reorder_level',
          'receiving_quantity',
          'category_id'
      ];

  public $fillable = [
      'upc_ean_isbn',
      'name',
      'description',
      'avatar',
      'cost_price',
      'selling_price',
      'quantity',
      'is_item_kit',
      'is_stockeable',
      'reorder_level',
      'receiving_quantity',
      'category_id'
  ];

  /**
   * The attributes that should be casted to native types.
   *
   * @var array
   */
  protected $casts = [
      'id' => 'integer',
      'upc_ean_isbn' => 'string',
      'name' => 'string',
      'description' => 'string',
      'avatar' => 'string',
      'quantity' => 'integer',
      'is_item_kit' => 'boolean',
      'is_stockeable' => 'boolean',
      'category_id' => 'integer'
  ];

  protected static function boot()
  {
      parent::boot();

      static::addGlobalScope('is_item_kit', function (Builder $builder) {
          $builder->where('is_item_kit', '=', 0);
      });
  }//

  /**
   * Validation rules
   *
   * @var array
   */
  public static $rules = [
      'name' => 'required|min:5',
      'avatar' => 'required',
      'cost_price' => 'required',
      'selling_price' => 'required',
      'quantity'  => 'required',
      'is_item_kit' => 'required',
      'is_stockeable'  => 'required',
      'reorder_level'  => 'required',
      'receiving_quantity'  => 'required',
  ];

  public function scopeOfSearch($query,$string)
  {
      if (trim($string) != ''){
        $query->orWhere('name','LIKE',"%".$string."%");
        $query->orWhere('upc_ean_isbn','LIKE',"%".$string."%");
        $query->orWhere('description','LIKE',"%".$string."%");
      }
      return $query;
  }

  public function scopeOfOption($query,$array_option)
  {
    if (empty($array_option) ) return $query;

      foreach ($array_option as $key => $value) {
        if ($value == 'reorder_level_down'){
          $query->whereColumn('items.reorder_level','>=','items.quantity');
        }
        if ($value == 'without_cost_price'){
          $query->where('items.cost_price','=','0');
        }
        if ($value == 'without_selling_price'){
          $query->where('items.selling_price','=','0');
        }
        if ($value == 'only_stockeable'){
          $query->where('items.is_stockeable','=','1');
        }
      }
      return $query;
  }
}

app/Http/Controllers/Api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Item;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $query = $request->input('query');
      $options =  $request->input('options');
      return item::ofSearch($query)
      ->select(['id','upc_ean_isbn','name','description','selling_price','quantity','cost_price','reorder_level'])
      ->ofOption($options)
      ->paginate(25)->appends(['query' => $query]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Item;
use App\Models\Stock;
use App\Models\Price;
class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('items.index',compact('items'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $item = Item::find($id);
      return view('items.show',compact('item'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new Item();
        return view('items.create',compact('item'));
    }

    /**
     * Show the form for creating a new resource.
     * @param in $id
     * @return \Illuminate\Http\Response
     */
    public function copy($id)
    {
        $item = Item::findOrFail($id);
        return view('items.create',compact('item'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'upc_ean_isbn' => 'required|unique:items,upc_ean_isbn',
           'name' => 'required'
        ]);
        $request->name = strtoupper($request->name);
        $input = $request->all();

          \DB::beginTransaction();
          $item = Item::create($input);

          $this->saveStock($item, $request->quantity, $request->remarks,true);
          Price::create(
              [
                'price'=> $request->cost_price,
                'sell_cost' => 'cost',
                'item_id' => $item->id,
                'user_id' => \Auth::user()->id,
                'remarks' => 'by New Item '
              ]);

          Price::create(
              [
                'price'=> $request->selling_price,
                'sell_cost' => 'sell',
                'item_id' => $item->id,
                'user_id' => \Auth::user()->id,
                'remarks' => 'by New Item '
              ]);

          \DB::commit();

        return redirect('/items');
    }

    public function saveStock(Item $item, $quantity, $remarks,$initial = false)
    {
        if( ($quantity - $item->quantity) != 0 || $initial){
          $stock = new Stock;
          $stock->item_id = $item->id;
          $stock->user_id = \Auth::user()->id;
          $stock->quantity = $initial ? $quantity: $quantity - $item->quantity ;
          $stock->in_out = $stock->quantity > 0 ? 'in': 'out';
          $stock->remarks = $remarks ? $remarks: 'Manual Edit of Quantity';
          $stock->save();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $item = Item::findOrFail($id);

      if (empty($item)) {
          return redirect(route('items.index'));
      }

      return view('items.edit')->with('item', $item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
         'upc_ean_isbn' => 'required',
         'name' => 'required'
      ]);

      $item = Item::findOrFail($id);

      if (empty($item)) {

          return redirect(route('items.index'));
      }
      $this->saveStock($item, $request->quantity, $request->remarks);

      if ($request->cost_price <> $item->cost_price)
      {
        Price::create(
            [
              'price'=> $request->cost_price,
              'sell_cost' => 'cost',
              'item_id' => $item->id,
              'user_id' => \Auth::user()->id,
              'remarks' => 'by Manual Update'
            ]);
      }

      if ($request->selling_price <> $item->selling_price)
      {
        Price::create(
            [
              'price'=> $request->selling_price,
              'sell_cost' => 'sell',
              'item_id' => $item->id,
              'user_id' => \Auth::user()->id,
              'remarks' => 'by Manual Update'
            ]);
      }

      $item->update($request->all(), ['id' => $id]);


      return redirect(route('items.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

      $item = Item::findOrFail($id);

      if (empty($item)) {
        return redirect(route('items.index'));
      }

      $item->delete($id);

      return redirect(route('items.index'));
    }
}

resources/views/items/create.blade.php
@extends('layouts.standart')

@section('title',__('Item Create'))

@section('body')
<form action="{!! route('items.store') !!}" method="POST">
   {{ csrf_field() }}
  @include('items.fields')
</form>

@endsection

resources/views/items/edit.blade.php
@extends('layouts.standart')

@section('title',__('Item'))

@section('title-right')
  <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('items.index') !!}">@lang('Back to List')</a>
@endsection

@section('body')
  <form action="{!! route('items.update',[$item->id]) !!}" method="post">
    {{ method_field('PATCH') }}
    {{ csrf_field() }}
    @include('items.fields')
  </form>
@endsection

resources/views/items/fields.blade.php
<div class="row">
  <!-- Upc Ean Isbn Field -->
  <div class="form-group col-md-3">
      <label for="upc_ean_isbn">@lang('Barcode'):</label>
      <input type="number" name="upc_ean_isbn" id="upc_ean_isbn" class="form-control" value="{{ old('upc_ean_isbn',(isset($item->upc_ean_isbn) ? $item->upc_ean_isbn: ''))}}"/>
  </div>
  <!-- Name Field -->
  <div class="form-group col-md-4">
      <label for="name">@lang('Name'):</label>
      <input type="text" name="name" id="name" onkeyup="this.value = this.value.toUpperCase()" class="form-control" value="{{ old('name',(isset($item->name) ? $item->name: ''))}}"/>
  </div>
  <!-- Description Field -->
  <div class="form-group col-md-5">
      <label for="description">@lang('Description'):</label>
      <input type="text" name="description" onkeyup="this.value = this.value.toUpperCase()" id="description" class="form-control"   value="{{ old('description',(isset($item->description) ? $item->description: ''))}}"/>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-md-3">
    <!-- Avatar Field -->
    <div class="form-group">
        <label for="avatar">Avatar:</label>
        <input type="text" name="avatar" id="avatar" class="form-control" value="{{ old('avatar',(isset($item->avatar) ? $item->avatar: 'no-photo.png'))}}" />
    </div>

    <!-- Type Field -->
    <div class="form-group">
          <label for="is_item_kit">@lang('Is Item Kit'):</label>
        <label class="checkbox-inline">

          @isset($item)
          <label for="is_item_kit">@lang('Yes'):</label>
          <input type="radio" name="is_item_kit" id="is_item_kit" value="1" {{ old('is_item_kit',$item->is_item_kit) == 1  ? "checked": "" }} />
          <label for="is_item_kit">@lang('No'):</label>
          <input type="radio" name="is_item_kit" id="is_item_kit" value="0" {{ old('is_item_kit',$item->is_item_kit) == 0  ? "checked": "" }} />
          @else
          <label for="is_item_kit">@lang('Yes'):</label>
          <input type="radio" name="is_item_kit" id="is_item_kit" value="1" checked />
          <label for="is_item_kit">@lang('No'):</label>
          <input type="radio" name="is_item_kit" id="is_item_kit" value="0"/>

          @endisset

    </div>

    <!-- Stock Type Field -->
    <div class="form-group">
      <label for="is_stockeable">@lang('Stock Type'):</label>
      <label class="checkbox-inline">
          <label for="is_stockeable">@lang('Stockeable'):</label>
          @isset ($item)
            <input type="radio" name="is_stockeable" id="is_stockeable" value="1" {{ old('is_stockeable',$item->is_stockeable) == 1 ? "checked": '' }} />
            <label for="is_stockeable">@lang('Unstockeable'):</label>
            <input type="radio" name="is_stockeable" id="is_stockeable" value="0" {{ old('is_stockeable',$item->is_stockeable) == 0 ? "checked": '' }}/>
          @else
            <input type="radio" name="is_stockeable" id="is_stockeable" value="1" checked />
            <label for="is_stockeable">@lang('Unstockeable'):</label>
            <input type="radio" name="is_stockeable" id="is_stockeable" value="0" />
          @endisset
      </label>
    </div>

  </div>
  <div class="col-xs-4 col-md-4">
    <!-- Cost Price Field -->
    <div class="form-group">
      <label for="cost_price">@lang('cost_price'):</label>
      <input type="number" step=".01" name="cost_price" id="cost_price" class="form-control" value="{{ old('cost_price',(isset($item->cost_price) ? $item->cost_price: '0.00'))}}"/>
    </div>

    <!-- Selling Price Field -->
    <div class="form-group">
      <label for="selling_price">@lang('selling_price'):</label>
      <input type="number" step=".01" name="selling_price" id="selling_price" class="form-control" value="{{ old('selling_price',(isset($item->selling_price) ? $item->selling_price: '0.00'))}}" />
    </div>

    <!-- Quantity Field -->
    <div class="form-group">
      <label for="quantity">@lang('quantity'):</label>
      <input type="number" name="quantity" id="quantity" class="form-control" value="{{ old('quantity',(isset($item->quantity) ? $item->quantity: '0'))}}"/>
    </div>

  </div>
  <div class="col-xs-4 col-md-4">
    <!-- Reorder Level Field -->
    <div class="form-group">
      <label for="reorder_level">@lang('reorder_level'):</label>
      <input type="number" name="reorder_level" id="reorder_level" class="form-control" value="{{old('reorder_level',is_null($item->reorder_level) ? '0': $item->reorder_level )}}"/>
    </div>

    <!-- Receiving Quantity Field -->
    <div class="form-group">
      <label for="receiving_quantity">@lang('receiving_quantity'):</label>
      <input type="number" name="receiving_quantity" id="receiving_quantity" class="form-control" value="{{old('receiving_quantity',is_null($item->receiving_quantity) ? '0': $item->receiving_quantity )}}"/>
    </div>

  </div>
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    <button type="submit" class="btn btn-primary">@lang('Save')</button>
    <a href="{!! route('items.index') !!}" class="btn btn-default">@lang('Cancel')</a>
</div>

resources/views/items/index.blade.php
@extends('layouts.standart')

@section('title',__('Items'))

@section('title-right')
  <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('items.create') !!}">@lang('Add New')</a>
@endsection

@section('body')
  @include('items.table')
@endsection

resources/views/items/show.blade.php
@extends('layouts.standart')

@section('title','Item Show')

@section('title-right')
  <a href="{!! route('items.index') !!}" class="btn btn-info">Back</a>
@endsection

@section('body')
  @include('items.show_fields')
@endsection

resources/views/items/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $item->id !!}</p>
</div>

<!-- Upc Ean Isbn Field -->
<div class="form-group">
    {!! Form::label('upc_ean_isbn', __('Barcode').':') !!}
    <p>{!! $item->upc_ean_isbn !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $item->name !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $item->description !!}</p>
</div>

<!-- Avatar Field -->
<div class="form-group">
    {!! Form::label('avatar', 'Avatar:') !!}
    <p>{!! $item->avatar !!}</p>
</div>

<!-- Cost Price Field -->
<div class="form-group">
    {!! Form::label('cost_price', 'Cost Price:') !!}
    <p>{!! $item->cost_price !!}</p>
</div>

<!-- Selling Price Field -->
<div class="form-group">
    {!! Form::label('selling_price', 'Selling Price:') !!}
    <p>{!! $item->selling_price !!}</p>
</div>

<!-- Quantity Field -->
<div class="form-group">
    {!! Form::label('quantity', 'Quantity:') !!}
    <p>{!! $item->quantity !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $item->type !!}</p>
</div>

<!-- Stock Type Field -->
<div class="form-group">
    {!! Form::label('is_stockeable', 'Stock Type:') !!}
    <p>{!! $item->is_stockeable !!}</p>
</div>

<!-- Reorder Level Field -->
<div class="form-group">
    {!! Form::label('reorder_level', 'Reorder Level:') !!}
    <p>{!! $item->reorder_level !!}</p>
</div>

<!-- Receiving Quantity Field -->
<div class="form-group">
    {!! Form::label('receiving_quantity', 'Receiving Quantity:') !!}
    <p>{!! $item->receiving_quantity !!}</p>
</div>

<!-- Category Id Field -->
<div class="form-group">
    {!! Form::label('category_id', 'Category Id:') !!}
    <p>{!! $item->category_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $item->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $item->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $item->deleted_at !!}</p>
</div>

resources/views/items/table.blade.php
<div id="app">
<div class="row">
  <div class="col-md-5">
    @include('layouts.parts.field_search')
    <p v-if="pagination.current_page > 0">Total found: @{{ pagination.total }}</p>
    <p v-if="pagination.current_page > 0">@lang('Page'): @{{ pagination.current_page}} @lang('of') @{{ pagination.last_page}}</p>
</div>
<div class="col-md-7">
  <div class="form-inline">
    <label class="form-label" for="query">@lang('Reorder Level Down'):</label>
    <input type="checkbox" name="options[]" v-model="options" value="reorder_level_down" /><br/>
    <label class="form-label" for="query">@lang('Without Cost Price'):</label>
    <input type="checkbox" name="options[]" v-model="options" value="without_cost_price" /><br/>
    <label class="form-label" for="query">@lang('Without Selling Price'):</label>
    <input type="checkbox" name="options[]" v-model="options" value="without_selling_price" /><br/>
    <label class="form-label" for="query">@lang('Only Stockeables'):</label>
    <input type="checkbox" name="options[]" v-model="options" value="only_stockeable" />
  </div>
</div>

</div>

  <div class="table-responsible">
    <table class="table table-striped table-condensed">
      <thead>
        <th>@lang('Barcode') - @lang('Item')</th>
        <th class="hidden-xs">@lang('Cost Price')</th>
        <th>@lang('Selling Price')</th>
        <th>@lang('Quantity')</th>
        <th>Action</th>
      </thead>
      <tbody>
        <tr v-for="row in rows">
            <td>@{{ row.upc_ean_isbn }} - @{{ row.name }}</td>
            <td class="hidden-xs">@{{ row.cost_price }}</td>
            <td>@{{ row.selling_price }}</td>
            <td>@{{ row.quantity }}</td>
            <td>
                <action_icons url="{{ url('items') }}" :id="row.id"></action_icons>
            </td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
            <td colspan="5">
              <ul class="pagination">
                 <li v-if="pagination.current_page > 1">
                     <a href="javascript:void(0)" aria-label="Previous" v-on:click.prevent="changePage(pagination.current_page - 1)">
                         <span aria-hidden="true">«</span>
                         </a>
                     </li>
                 <li v-for="page in pagination.last_page" :class="{'active': page == pagination.current_page}">
                     <a href="javascript:void(0)" v-on:click.prevent="changePage(page)">@{{ page }}</a>
                     </li>
                 <li v-if="pagination.current_page < pagination.last_page">
                     <a href="javascript:void(0)" aria-label="Next" v-on:click.prevent="changePage(pagination.current_page + 1)">
                         <span aria-hidden="true">»</span>
                         </a>
                     </li>
                 </ul>
            </td>
        </tr>
      </tfoot>
    </table>

  </div>
</div>

@section('js')

  <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.0"></script>

  <script type="text/template" id="show_icon">
    <a :href="getUrl(url,id)" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-eye-open"></i></a>
  </script>

  <script type="text/template" id="edit_icon">
    <a :href="getUrl(url,id)" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-edit"></i></a>
  </script>

  <script type="text/template" id="copy_icon">
    <a :href="getUrl(url,id)" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-duplicate"></i></a>
  </script>

  <script type="text/template" id="action_icons">
    <form :action="url + '/' + id" method="POST">
      <div class='btn-group'>
          {{ method_field('DELETE') }}
          {{ csrf_field() }}
          <show_icon :url="url" :id="id"></show_icon>
          <edit_icon :url="url" :id="id"></edit_icon>
          <copy_icon :url="url" :id="id"></copy_icon>
          <button class ="btn btn-danger btn-sm" type="submit" onclick="return confirm('Are you sure?')"><i class="glyphicon glyphicon-trash"></i></button>
      </div>
    </form>
  </script>

  <script type="text/javascript">
    Vue.component('show_icon',{
        template: '#show_icon',
        props: ['url','id'],
        methods: {
          getUrl: function (url,id){
            return url + "/" + id;
          }
        }
      });
  </script>

  <script type="text/javascript">
    Vue.component('edit_icon',{
        template: '#edit_icon',
        props: ['url','id'],
        methods: {
          getUrl: function (url,id){
            return url + "/" + id + "/edit";
          }
        }
      });
  </script>

  <script type="text/javascript">
    Vue.component('copy_icon',{
        template: '#copy_icon',
        props: ['url','id'],
        methods: {
          getUrl: function (url,id){
            return url + "/" + id + "/copy";
          }
        }
      });
  </script>

  <script type="text/javascript">
    Vue.component('action_icons',{
        template: '#action_icons',
        props: ['url','id']
      });
  </script>

  <script type="text/javascript">
      var vm =  new Vue({
        el: "#app",
        data: {
            rows: [],
            selected: '',
            query: '',
            pagination: [{ 'prev_page_url': 0 }],
            options:[],
        },
        methods:{
          getItems: function (query, page){
            var options = "";
            this.options.forEach(function(entry) {
              options += "&options[]=" + entry;
            });
            this.$http.get('{!! url('api/items')!!}'+ '?query=' + query + "&page=" + page + options).then(function(response){
                this.rows = response.body.data;
                this.pagination = response.body;
            });
          },
          changePage(page) {
            this.getItems(this.query, page);
            this.pagination.current_page = page;
          }
        }
    });
  </script>

  @endsection